Passthrough `onlyOperationTypes` in client-preset
dotansimha/graphql-code-generator pull request #10155
Opened 2024-09-28 21:46 UTC by nebbles

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

Passes through the `onlyOperationTypes` config option for the client preset.

It defaults to `false` however it would be useful focusing type generation on just the operations, reducing bundle size and developer error (a frequent one for us, building dependency on the wrong types).

As discussed in https://github.com/dotansimha/graphql-code-generator/discussions/8693

## Type of change

New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2024-10-07 16:30 UTC, saihaj requested changes
needs a rebase. Also please create a `minor` changeset for this so we can have release changelog

2024-10-10 20:09 UTC, nebbles commented
Thanks @saihaj. Will make the changes requested! (I'm assuming changesets are generated with `npx changeset`)

2024-10-11 07:44 UTC, nebbles commented
@saihaj I have made a minor adjustment to this PR to include passing through `onlyEnumTypes`.

This is the aim of my PR was achieved in https://github.com/dotansimha/graphql-code-generator/pull/10073 but via changing the under-the-hood behaviour of client-preset. As seen on that PR, there has been pushback as this has changed outputs for the preset in a way consumers had relied on.

I suggest that PR is reverted for the sake of those affected. Separately, this PR will allow those of us who want to reduce the size of the generated types to opt-in via these two configuration options.

2024-12-23 16:33 UTC, saihaj approved these changes
thanks!

2024-12-23 16:33 UTC, merged

2025-02-05 09:28 UTC, konomae commented on packages/presets/client/src/index.ts
> +      onlyEnumTypes: options.config.onlyEnumTypes,
I think this is not correct...?

https://the-guild.dev/graphql/codegen/plugins/typescript/typescript#onlyenums

```suggestion
      onlyEnums: options.config.onlyEnums,
```

2025-02-05 09:43 UTC, konomae commented on packages/presets/client/src/index.ts
> +      onlyEnumTypes: options.config.onlyEnumTypes,
- https://github.com/dotansimha/graphql-code-generator/pull/10280