feat(plugin/typescript-resolvers): Add allowSemanticNonNull option
dotansimha/graphql-code-generator pull request #10159
Opened 2024-10-01 09:31 UTC by Quramy

## Description

Related #10151 .

Added a new option for plugin/typescript-resolvers, `allowSemanticNonNull`.

Several GraphQL frameworks work with `@semanticNonNull` schema directive:

- https://relay.dev/docs/guides/semantic-nullability/#proposed-solution
- https://www.apollographql.com/docs/kotlin/advanced/nullability/#semanticnonnull

If `allowSemanticNonNull` option is set to `true`, field resolver annotated by `@semanticNonNull` gets prohibited to return nullish.

For example:

```gql
type User {
  name: String @semanticNonNull
}
```

The above schema and `allowSemanticNonNull: true` generates the following resolver type:

```ts
export type UserResolvers<ContextType = BaseContext, ParentType extends ResolversParentTypes['User'] = ResolversParentTypes['User']> = {
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};
```

```ts
import type { UserResolvers } from "./_gql_gen_generated_/"

export const User = {
  name:  () => {
    // @ts-expect-error
    return null;
  }
} satisfies UserResolvers
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Unit Testing

**Test Environment**:

- OS: macos Sonoma
- NodeJS: v20.14.0

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

2025-03-12 10:22 UTC, alf requested changes
Fix spelling of transform

2025-03-12 10:22 UTC, alf commented on packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
> +  protected tranceformSemanticNonNull(type: string): string {
```suggestion
  protected transformSemanticNonNull(type: string): string {
```

2025-03-12 10:22 UTC, alf commented on packages/plugins/other/visitor-plugin-common/src/base-resolvers-visitor.ts
> +        ? this.tranceformSemanticNonNull(mappedType)
```suggestion
        ? this.transformSemanticNonNull(mappedType)
```

2025-03-12 10:22 UTC, alf commented on packages/plugins/typescript/resolvers/src/visitor.ts
> +  }
```suggestion
  protected transformSemanticNonNull(type: string): string {
    if (this.config.allowSemanticNonNull) {
      return this.clearOptional(super.transformSemanticNonNull(type));
    }
    return super.transformSemanticNonNull(type);
  }
```

2025-03-12 13:07 UTC, eddeee888 commented on packages/plugins/typescript/resolvers/src/config.ts
> +  allowSemanticNonNull?: boolean;
Should we add the new config to the `base-resolvers-visitor`? 
This directive feels like something it should know to handle 🙂

2025-03-12 13:09 UTC, eddeee888 commented on packages/plugins/typescript/resolvers/src/config.ts
> +  allowSemanticNonNull?: boolean;
There's a pattern in another base plugin that we use `customDirectives` key to group non-base GraphQL spec directives together. I imagine we could do the same here:

```ts
customDirectives?: {
  semanticNonNull?: boolean
}
```

2025-03-12 13:10 UTC, eddeee888 commented
Hi @Quramy , could you please add a changeset so we can release alpha versions? 🙂

2025-03-16 11:12 UTC, eddeee888 commented
Hi @Quramy @alf , I have created https://github.com/dotansimha/graphql-code-generator/pull/10315 based on this PR to help move the convo along. 
Thanks for the initial implementation!

2025-03-16 11:12 UTC, closed without merging