add new documents input type
dotansimha/graphql-code-generator pull request #7304
Opened 2022-01-02 15:35 UTC by gilgardosh

Related #7213

2022-01-04 17:22 UTC, dotansimha requested changes

2022-01-04 17:22 UTC, dotansimha commented on packages/graphql-codegen-cli/tests/codegen.spec.ts
> +            require: './tests/test-documents/valid.graphql',
The goal was actually to do it the other way around. 

So you can use a loader, and pass config to it: 

```
require: ./tests/custom-loaders/custom-documents-loader.js
config:
   loadFilesFrom: "./tests/test-documents/valid.graphql"
```

2022-02-07 09:29 UTC, charlypoly commented
@gilgardosh are we good to go? 🚢 
If so, I can take care of rebasing the PR and merging it

2022-02-07 09:30 UTC, charlypoly commented on .changeset/silly-clouds-play.md
> +Supoport loading documents by require+config structure
```suggestion
Support loading documents by require+config structure
```

2022-02-07 09:36 UTC, charlypoly commented
@gilgardosh could you confirm if the following looks correct to you? 

https://github.com/dotansimha/graphql-code-generator/pull/7304/files#diff-e51ca8ddc81d655b7024e6d82e2911acd04d919909db7b23d312c1c056feaa49R273

Thanks!

2022-02-07 13:55 UTC, gilgardosh commented
@charlypoly Looks great, thank you!

2022-02-07 14:56 UTC, closed without merging

2022-02-07 14:57 UTC, charlypoly commented
Discussed with @gilgardosh, will be done in `graphql-tools`.