feat: useLazyQuery for vue-apollo plugin
dotansimha/graphql-code-generator pull request #7340
Opened 2022-01-09 03:17 UTC by snowhork

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

## Description

Support `useLazyQuery` for vue-apollo plugin

Related #5258

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] execute `yarn test-and-build`, and check passed.
- [x] execute `generate:examples`, and commit it.

**Test Environment**:
- OS: macOS 11.6.1
- `@graphql-codegen/...`: e1285609a9cb08a8f15e75254ca8fc7d1684d4ad
- NodeJS: v17.0.1

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-01-09 04:16 UTC, snowhork commented
Please review at your convenience.

2022-01-27 10:18 UTC, charlypoly requested changes
Hi @snowhork, thank you for your contribution! ⚡ 

One small change request and we are good to go! 🚢

2022-01-27 10:18 UTC, charlypoly commented on packages/plugins/typescript/vue-apollo/src/visitor.ts
> +    let compositionFunction = this.buildCompositionFunction({
```suggestion
    const compositionFunctions = [this.buildCompositionFunction({
```

prefer moving it as an array and use a `.join("\n")` in the return

2022-01-27 10:18 UTC, charlypoly commented on packages/plugins/typescript/vue-apollo/src/visitor.ts
> +    }
```suggestion
      compositionFunctions.push(
        '\n' +
        this.buildCompositionFunction({
          operationName: lazyOperationName,
          operationType: lazyOperationType,
          operationResultType,
          operationVariablesTypes,
          operationHasNonNullableVariable,
          operationHasVariables,
          documentNodeVariable,
        });
      )
    }
```

2022-01-27 10:18 UTC, charlypoly commented on packages/plugins/typescript/vue-apollo/src/visitor.ts
>        compositionFunction,
refactor to a `compositionFunctions.join("\n")`

2022-01-30 04:51 UTC, snowhork commented
@charlypoly Thanks for your review! Please re-review!

2022-01-31 09:43 UTC, sschneider-ihre-pvs commented
🤙 can't wait to have lazyqueries !!

2022-01-31 09:52 UTC, charlypoly approved these changes

2022-01-31 09:53 UTC, merged