fix: Remove explicit return types from sdk methods
dotansimha/graphql-code-generator pull request #7592
Opened 2022-02-28 19:51 UTC by P4sca1

## Description

Previously, the return type of all SDK methods was declared manually. This can
cause the return type to become outdated when graphql-request gets updated.
This already happened, as graphql-request removed the errors attribute from the
return type (see https://github.com/prisma-labs/graphql-request/issues/174).
Also, `data` was marked as possibly undefined which is wrong. `data` always exists
on a successful response (failed requests throw a `ClientError`).

A sideeffect of this change is that the `extensionsType` config became obsolete
and has been removed. Because of this, I marked this change as a breaking change.

## Type of change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

I removed tests for the now removed `extensionsType` config and ran `yarn test -u`.  All tests are still passing. I also tested the change in a private project and did not experience any issues with the change.

2022-03-14 09:41 UTC, charlypoly commented
Hi @P4sca1,

The `extensionTypes` config has been [added quite recently](https://github.com/dotansimha/graphql-code-generator/pull/6969), it seems a bit premature to simply drop it because of concern around the future typing changes of `graphql-request`.
Typing `extensions` when using `rawRequest` is a legit use-case.
In order to completely remove the `extensionTypes` option without dropping this use-case, a good approach would be to [patch `graphql-request` to provide `extensions` generic type parameter](https://github.com/prisma-labs/graphql-request/blob/24ca53bafb4c7f777ab124604345cb64ad3cf301/src/index.ts#L201).

For now, we should especially fix the `data` as a non-undefined property and make the typings evolve in time.

2022-03-17 10:25 UTC, charlypoly requested changes
cf: https://github.com/dotansimha/graphql-code-generator/pull/7592#issuecomment-1066571735

2022-03-22 11:24 UTC, P4sca1 commented
I agree, we should wait for `graphql-request` to provide the ability to change the `extensions` type, before making this change.
In the mean time, I will make a seperate PR to fix the current typings.

2022-03-22 13:09 UTC, charlypoly commented
> In the mean time, I will make a seperate PR to fix the current typings.

Thank you @P4sca1!

2022-03-22 18:00 UTC, closed without merging