React query use type imports
dotansimha/graphql-code-generator pull request #7667
Opened 2022-03-19 04:08 UTC by jonathanstanley

## Description

corrects behavior so that `typescript-react-query` respects `useTypeImports` flag

Related # (issue)
#7666 main issue
#7661 related, but only the graphql-request fetcher portion

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

tested locally

**Test Environment**:
n/a

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-03-19 04:47 UTC, jonathanstanley commented
tests pass locally.

```
yarn test packages/plugins/typescript/react-query  

Test Suites: 1 passed, 1 total
Tests:       31 passed, 31 total
Snapshots:   12 passed, 12 total
Time:        0.658 s, estimated 1 s
```
i don't know why dev-tests failing here.

2022-03-21 09:01 UTC, charlypoly requested changes
Hi @jonathanstanley,

Thank you for your work!
I have 2 feedback:
- It would be preferable that imports from the same source are grouped (cf inlined comment)
- Could you add tests when `useTypeImports` is used?

Thank you!

2022-03-21 13:35 UTC, jonathanstanley commented on packages/plugins/typescript/react-query/src/visitor.ts
> +    ];
yes; i'll add a commit shortly

2022-03-21 13:35 UTC, jonathanstanley commented on packages/plugins/typescript/react-query/src/visitor.ts
> +    ];
> * Could you add tests when `useTypeImports` is used?
it is in there... just a bit buried:
https://github.com/dotansimha/graphql-code-generator/blob/6cdb68b9123dccc80009b2af9ac66bb7de961cd9/packages/plugins/typescript/react-query/tests/react-query.spec.ts#L528

2022-03-21 14:14 UTC, jonathanstanley commented on packages/plugins/typescript/react-query/src/visitor.ts
> +    ];
done:
https://github.com/dotansimha/graphql-code-generator/pull/7667/commits/799405d26a65c329a2614c5e9da1825d99c748c2#diff-38f7b7f89098e5486e40c54e00569d09eb7b873bc8d4a7118aa39a1ce1c1be68

also adjusted tests

2022-03-21 14:47 UTC, charlypoly approved these changes
Thank you for the fast changes @jonathanstanley! ⚡

2022-03-21 14:48 UTC, merged