Generate ` $fragmentName` for fragment subtypes for fragment masking
dotansimha/graphql-code-generator pull request #7813
Opened 2022-05-02 08:11 UTC by izumin5210

## Description

Related #7811 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-05-03 16:17 UTC, n1ru4l commented on packages/plugins/typescript/operations/tests/ts-documents.spec.ts
> +        #graphql
```suggestion

```

2022-05-03 16:20 UTC, n1ru4l commented on packages/plugins/typescript/operations/tests/ts-documents.spec.ts
> +        #graphql
We don't need this comment here.

2022-05-03 16:45 UTC, n1ru4l requested changes
Thank you for this contribution, there is just one small suggested change, once that one is resolved we are ready to merge.

It would also be nice if you could update the dev-tests to also include fixtures for the cases you highlighted in the tests.

2022-05-04 11:17 UTC, izumin5210 commented
Thank you four your code review 😄 

I have added a new dev-test for complex cases ✅ 
👉  b0d6b8d

2022-05-04 11:26 UTC, n1ru4l approved these changes
Awesome 🎉

2022-05-04 11:31 UTC, merged