allow mappers config overriding
dotansimha/graphql-code-generator pull request #8125
Opened 2022-07-21 08:17 UTC by cometkim

## Description

When workspaces include multiple GraphQL projects, and graphs share the same core model. In this case, I would like to write the core model mappers only once in the root config and additional mappers per plugin, but that is not currently allowed.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I skipped it because there are no existing tests for config. Please tell me if it requires

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-01 12:20 UTC, charlypoly requested changes
Hi @cometkim!

Thank you for your proposal; it definitely would help codegen work better on large-scale or monorepo projects; we are definitely looking forward to having this new behavior merged! ⚡ 

Your proposed changes won't allow set `mappers` at the root level of the config since you're getting the current `mappers` values from the generates section.
To get `mappers` to be defined and fetched from the root of the config, you'll need to introduce changes related to the [`Config`](https://github.com/dotansimha/graphql-code-generator/blob/2cbcbb37101708705ab94cec747997c8063f698d/packages/utils/plugins-helpers/src/types.ts#L345) type.

Let me know if we can help!

2022-08-02 05:54 UTC, cometkim commented
@charlypoly I expect that the JSONSchema for editor support is also need to be changed. Is it automatically generated? Or is it managed elsewhere?

2022-08-02 08:00 UTC, charlypoly commented
Hi @cometkim,

What do you mean by "JSONSchema for editor support"?

2022-08-02 10:45 UTC, cometkim commented
I meant this https://www.graphql-code-generator.com/config.schema.json

2022-08-03 08:24 UTC, charlypoly commented
> I meant this https://www.graphql-code-generator.com/config.schema.json

This file is automatically generated

2022-08-03 11:28 UTC, charlypoly commented
@cometkim, I've fixed your PR to support the following configuration:

```yml
schema: "schema.graphql"
documents: src/*.ts
mergeMappers: true
config:
    mappers:
      ID: IDType
generates:
  resolvers-types-1.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      mappers:
        String: StringType
  resolvers-types-2.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      mappers:
        String: StringType
```

Example setup is available here: https://github.com/charlypoly/codegen-repros/tree/master/merged-config

You can see that I added a `mergeMappers` flag (default: `false`) since introducing this change will be breaking for most configurations.

Let me know what you think 👀

2022-08-03 11:41 UTC, charlypoly commented
@cometkim, actually, this new options is not necessary since you can achieve same result using YAML references: 
[codegen.yml](https://github.com/charlypoly/codegen-repros/blob/master/reusable-mappers/codegen.yml)

```yaml
schema: "schema.graphql"
documents: src/*.ts

shared_mappers: &shared_mappers
  ID: IDType

generates:
  resolvers-types-1.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      mappers:
        <<: *shared_mappers
        String: StringType
  resolvers-types-2.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      mappers:
        <<: *shared_mappers
        String: StringType
```


I'm closing this PR and will update the `typescript-resolvers` documentation with the above example

2022-08-03 11:41 UTC, closed without merging

2022-08-03 11:47 UTC, charlypoly commented
https://github.com/dotansimha/graphql-code-generator/pull/8177