Added  option to graphql-request for allowing generation of individua…
dotansimha/graphql-code-generator pull request #8131
Opened 2022-07-22 11:06 UTC by cipriancaba

…l method exports as opposed to a wrapped sdk

## Description

This new flag in `typescript-graphql-request` should offer the possibility to generate individual operation functions as opposed to wrapping everything in an expensive `getSdk` object. 

This would allow compilers like webpack to correctly treeshake the code used and significantly decrease the initial bundle size for frontend apps

Related #6210 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-27 10:47 UTC, cipriancaba commented
Hey @charlypoly , do you have any input on this implementation?

2022-07-27 15:07 UTC, charlypoly requested changes
Hi @cipriancaba!

Thank you for your proposal!
Here are some feedback on your PR:

- [ ] the implementation could be done in a cleaner way (see code comment)
- [ ] the docs need to be updated (how to configure and use this new option), [see this file](https://github.com/dotansimha/graphql-code-generator/blob/16a1d81542cb1856a99eb2a946d1aab4f3381cc3/website/src/pages/plugins/typescript/typescript-graphql-request.mdx)
- [ ] it would be great to add a new `dev-test` use-case, [see this codegen file](https://github.com/dotansimha/graphql-code-generator/blob/5c7592b4dde8a8035c33eeeb89a1682cdf2a34fa/dev-test/codegen.yml)


Let me know if you have any questions!

2022-07-27 15:07 UTC, charlypoly commented on packages/plugins/typescript/graphql-request/src/visitor.ts
> +        } else if (this.config.generateIndividualOperations) {
I'm not comfortable with this implementation that "hijack" the SDK object properties building.

The code would be easier to read if the operations exports were handled earlier, for example, at line `111`.
Also, is there any motivation for dropping the support of wrappers for this new option?

2022-09-22 10:21 UTC, kaorun343 commented
any updates?

2022-09-22 12:35 UTC, charlypoly commented
Hi @kaorun343,

We are waiting for the review request changes to be addressed: https://github.com/dotansimha/graphql-code-generator/pull/8131#pullrequestreview-1052676585

2022-11-07 10:21 UTC, charlypoly commented
Hi!

All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
<details>
<summary>Community plugins:</summary>

- `@graphql-codegen/typescript-react-apollo`
- `@graphql-codegen/typescript-graphql-request`
- `@graphql-codegen/typescript-apollo-angular`
- `@graphql-codegen/typescript-apollo-client-helpers`
- `@graphql-codegen/typescript-react-query`
- `@graphql-codegen/typescript-urql`
- `@graphql-codegen/named-operations-object`
- `@graphql-codegen/urql-introspection`
- `@graphql-codegen/flow-resolvers`
- `@graphql-codegen/typescript-vue-apollo`
- `@graphql-codegen/typescript-rtk-query`
- `@graphql-codegen/flow-operations`
- `@graphql-codegen/typescript-msw`
- `@graphql-codegen/typescript-mongodb`
- `@graphql-codegen/typescript-type-graphql`
- `@graphql-codegen/jsdoc`
- `@graphql-codegen/typescript-vue-urql`
- `@graphql-codegen/kotlin`
- `@graphql-codegen/typescript-vue-apollo-smart-ops`
- `@graphql-codegen/java`
- `@graphql-codegen/c-sharp-operations`
- `@graphql-codegen/hasura-allow-list`
- `@graphql-codegen/typescript-stencil-apollo`
- `@graphql-codegen/relay-operation-optimizer`
- `@graphql-codegen/typescript-oclif`
- `@graphql-codegen/java-resolvers`
- `@graphql-codegen/java-apollo-android`
- `@graphql-codegen/flutter-freezed`

</details>

### Please move your PR by following these steps:

From your current PR branch:
- git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
- git fetch codegen-community
- git push codegen-community

Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.

Thank you!

2023-10-19 15:31 UTC, closed without merging