graphql-request: Specify explicit extension when importing dom types
dotansimha/graphql-code-generator pull request #8235
Opened 2022-08-14 12:51 UTC by just-boris

This is needed to support "moduleResolution": "nodenext" in typescript

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related #8022

## Type of change

It looks like the related issue attempted to add `.js` extensions to all imports, but this one got missing

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Modified generated code locally, it passes typescript compilation

**Test Environment**:

n/a

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

n/a

2022-08-15 07:32 UTC, n1ru4l requested changes
Hey there! The file extension should be added conditionally via the `emitLegacyCommonJSImports` flag, which we introduced here: https://github.com/dotansimha/graphql-code-generator/pull/8077

The reason for this is that some tools (such as Next.js) require additional configuration for being able to process the `.js` extension, thus we introduced it behind a flag for now.

See the following issues for a brief history:
- https://github.com/dotansimha/graphql-code-generator/pull/8034
- https://github.com/dotansimha/graphql-code-generator/issues/8065
- https://github.com/dotansimha/graphql-code-generator/issues/8065
- https://github.com/dotansimha/graphql-code-generator/pull/8077

2022-08-17 09:18 UTC, charlypoly requested changes

2022-08-17 09:18 UTC, charlypoly commented on packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
> +    this.visitor.imports.add(`${typeImport} { RequestInit } from 'graphql-request/dist/types.dom.js';`);
The same applies here, we need to rely on `emitLegacyCommonJSImports` config

2022-08-17 09:18 UTC, charlypoly commented on packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
> +    this.visitor.imports.add(`${typeImport} { RequestInit } from 'graphql-request/dist/types.dom.js';`);
The same applies here, we need to rely on `emitLegacyCommonJSImports` config

2022-08-22 12:47 UTC, charlypoly requested changes
Please update the plugin's test to pass `emitLegacyCommonJSImports: true` in `config` since it is the expected default behavior when `emitLegacyCommonJSImports` is missing at the `codegen.yml` level (the CLI normalizes `emitLegacyCommonJSImports` to `true` when missing, then pass its value to the plugins).
It will also prevent all those changes on the snapshots.

Thanks!

2022-09-07 15:24 UTC, jcarrus commented
Hi everyone. I just ran into this issue also and would like to help move this along. So excited to see a fix already in progress!

> Please update the plugin's test to pass `emitLegacyCommonJSImports: true` in `config` since it is the expected default behavior when `emitLegacyCommonJSImports` is missing at the `codegen.yml` level (the CLI normalizes `emitLegacyCommonJSImports` to `true` when missing, then pass its value to the plugins). It will also prevent all those changes on the snapshots.

@charlypoly, are you recommending to explicitly pass `emitLegacyCommonJSImports: true` to just be clear about what the default value is? Or is there some other reason?

It seems to me that the existing tests should stay the same and a new test should be added with `emitLegacyCommonJSImports: true` to verify that the extension is attached.

I've mocked these proposed changes here: #8334 if that's easier to see.

Let me know how we can move this forward!

2022-09-20 14:35 UTC, charlypoly commented
Close in favor of https://github.com/dotansimha/graphql-code-generator/pull/8334

2022-09-20 14:35 UTC, closed without merging