feat(apollo-client-helpers): optionally generate types for FieldPolicy
dotansimha/graphql-code-generator pull request #8510
Opened 2022-10-21 14:21 UTC by SimenB

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

I'm a rebel (I was prototyping if it was possible, and why not open a PR 😅)

## Description

Currently all type policies are typed as `any`, meaning no type safety in custom read functions.

Related # (issue) N/A

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

N/A

## How Has This Been Tested?

- In my own project
- Unit test

**Test Environment**:

- OS:
- `@graphql-codegen/...`:  `2.13.7`
- NodeJS: `16.18.0`

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

- I'm not sure about the `References` change. It should be allowed as return value, but this now also comes as `existing` to `merge` functions. Might just be a weakness in the Apollo types?
- Client fields are not in my `gqltypes`, not sure how to deal with it 😅 Shouldn't block an initial release, tho.

2022-10-24 09:11 UTC, charlypoly requested changes
Hi @SimenB,

Thank you for your contribution!

I've left a comment for ESM support.
Also, could you update this plugin documentation accordingly? https://www.the-guild.dev/graphql/codegen/plugins/typescript/typescript-apollo-client-helpers
(By updating this file: https://github.com/dotansimha/graphql-code-generator/blob/master/website/src/pages/plugins/typescript/typescript-apollo-client-helpers.mdx)

Thank you!

2022-10-24 09:11 UTC, charlypoly commented on packages/plugins/typescript/apollo-client-helpers/src/index.ts
> +        ? `import ${config.useTypeImports ? 'type ' : ''}* as Types from './${config.baseTypesPath}';`
Please make sure to provide support for ESM projects by leveraging the `emitLegacyCommonJSImports` option like other plugins do, for example here with the `graphql-request` plugin: 
https://github.com/dotansimha/graphql-code-generator/blob/e743f6984952cbdffa359a3a53eb4c50fe0d2879/packages/plugins/typescript/graphql-request/src/visitor.ts#L44-L47

2022-10-24 10:39 UTC, SimenB commented
> Also, could you update this plugin documentation accordingly?

I thought `PluginApiDocs` generated that automatically?

2022-10-25 12:37 UTC, charlypoly commented
> I thought `PluginApiDocs` generated that automatically?

@SimenB, it does but for this new flag, it would nice to introduce more complete example of the final usage.

2022-11-07 10:20 UTC, charlypoly commented
Hi!

All community plugins (see list below) have been moved to a new [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community).
<details>
<summary>Community plugins:</summary>

- `@graphql-codegen/typescript-react-apollo`
- `@graphql-codegen/typescript-graphql-request`
- `@graphql-codegen/typescript-apollo-angular`
- `@graphql-codegen/typescript-apollo-client-helpers`
- `@graphql-codegen/typescript-react-query`
- `@graphql-codegen/typescript-urql`
- `@graphql-codegen/named-operations-object`
- `@graphql-codegen/urql-introspection`
- `@graphql-codegen/flow-resolvers`
- `@graphql-codegen/typescript-vue-apollo`
- `@graphql-codegen/typescript-rtk-query`
- `@graphql-codegen/flow-operations`
- `@graphql-codegen/typescript-msw`
- `@graphql-codegen/typescript-mongodb`
- `@graphql-codegen/typescript-type-graphql`
- `@graphql-codegen/jsdoc`
- `@graphql-codegen/typescript-vue-urql`
- `@graphql-codegen/kotlin`
- `@graphql-codegen/typescript-vue-apollo-smart-ops`
- `@graphql-codegen/java`
- `@graphql-codegen/c-sharp-operations`
- `@graphql-codegen/hasura-allow-list`
- `@graphql-codegen/typescript-stencil-apollo`
- `@graphql-codegen/relay-operation-optimizer`
- `@graphql-codegen/typescript-oclif`
- `@graphql-codegen/java-resolvers`
- `@graphql-codegen/java-apollo-android`
- `@graphql-codegen/flutter-freezed`

</details>

### Please move your PR by following these steps:

From your current PR branch:
- git remote add codegen-community git@github.com:dotansimha/graphql-code-generator-community.git
- git fetch codegen-community
- git push codegen-community

Open the PR on [`dotansimha/graphql-code-generator-community`](https://github.com/dotansimha/graphql-code-generator-community) and close this PR.

Thank you!

2022-11-07 11:06 UTC, SimenB commented
yeeeeh, no

2022-11-07 11:06 UTC, closed without merging