Fix #7938
dotansimha/graphql-code-generator pull request #8586
Opened 2022-11-08 09:13 UTC by levrik

2022-11-08 09:32 UTC, levrik commented on packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
> +    const declarationKind = node.fields.length === 1 ? this._parsedConfig.declarationKind.input : 'type';
I'm a bit unsure about making a difference between single and multiple fields.
Please let me know what you would prefer.

2022-11-08 09:36 UTC, levrik commented on packages/plugins/other/visitor-plugin-common/src/base-types-visitor.ts
> +    const declarationKind = node.fields.length === 1 ? this._parsedConfig.declarationKind.input : 'type';
I'm a bit unsure about making a difference between single and multiple fields.
Please let me know what you would prefer.

2022-11-08 11:49 UTC, n1ru4l requested changes
This is great, can you please add a changeset that describes this change?

2022-11-08 12:49 UTC, levrik commented
@n1ru4l Added a changeset. I hope I did everything correct.

2022-11-11 13:58 UTC, levrik commented
@n1ru4l Is there anything more to be done?

2022-11-11 14:01 UTC, n1ru4l approved these changes

2022-11-11 14:28 UTC, n1ru4l commented
@levrik waiting for another review from @charlypoly - then we should be fine :)

2022-11-15 13:51 UTC, charlypoly approved these changes

2022-11-15 13:52 UTC, merged

2022-11-15 14:02 UTC, levrik commented
Thanks a lot for getting this merged!

2022-11-15 14:10 UTC, charlypoly commented
@levrik Thank you for fixing this! 🙇🏼