emitLegacyCommonJSImports IN graphqlmodulespreset
dotansimha/graphql-code-generator pull request #8805
Opened 2023-01-07 22:48 UTC by joaquimnetocel

When emitLegacyCommonJSImports is false, graphql-modules preset is generating imports without ".js" extension.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

2023-01-18 20:06 UTC, saihaj requested changes
can you add 
1. Tests 
2. `patch` changeset. Learn more: https://github.com/dotansimha/graphql-code-generator/pull/8805#issuecomment-1374641591

2023-01-22 23:45 UTC, joaquimnetocel commented
Unfortunately I don't know how to do it.

2023-03-30 16:55 UTC, closed without merging

2023-06-15 11:49 UTC, cantutar commented
Yep im getting the same problem, literally after if i need to build with tsc im doing manually adding .js's to imports.

2025-03-13 10:30 UTC, acharkov commented
Why this issue was closed without the merge?
Can I somehow help you to finalize it?