Stop importing fragments that are now unused
dotansimha/graphql-code-generator pull request #9136
Opened 2023-03-08 15:12 UTC by adrienharnay

## Description

After this change: https://github.com/dotansimha/graphql-code-generator/pull/8971, we see that fragments are still imported but now unused, resulting in a TS error.

Related # (issue): https://github.com/dotansimha/graphql-code-generator-community/issues/289

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] [Test A](https://codesandbox.io/s/gql-code-generator-without-dedup-fragments-forked-35lp34?file=/src/user.fragment.generated.tsx)
- [ ] Test B => same sandbox pointing to fork

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-03-10 07:54 UTC, n1ru4l commented
Thank you @adrienharnay, can you have a look at the failing CI please?

2023-03-14 22:20 UTC, dstaley commented
Just wanted to chime in with a specific description of the error that this PR fixes:

When using `preset: 'near-operation-file'` with `plugins: ['typescript-operations', 'typed-document-node']` the generated files contain import statements importing `*FragmentDoc` from the `baseTypesPath`. These imports are unused in the resulting file, but what's worse is that the `*FragmentDoc` that's being imported doesn't exist within the generated file at `baseTypesPath`. This results in errors like the following:

```
./components/GlobalHeadTags/fragment.graphql.generated.ts:4:10
Type error: Module '"types/dato"' has no exported member 'ImageFieldsFragmentDoc'.

  2 | 
  3 | import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
> 4 | import { ImageFieldsFragmentDoc } from 'types/dato'
```

I've confirmed that removing the code that @adrienharnay removed in this PR fixes the issue and produces a valid set of TypeScript files.

2023-05-24 22:28 UTC, dwknippers commented
Running into the same issue, if this PR is successful and merged that would be awesome!

2023-10-19 15:26 UTC, saihaj requested changes
please add a failing test case and fix lint issues

2023-11-01 20:02 UTC, closed without merging