Add gpt docs support
dotansimha/graphql-code-generator pull request #9419
Opened 2023-05-16 17:31 UTC by beerose

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Related # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Environment**:

- OS:
- `@graphql-codegen/...`:
- NodeJS:

## Checklist:

- [ ] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2023-05-25 16:56 UTC, beerose commented on website/package.json
> +    "@mendable/search": "^0.0.102",
```suggestion
    "@mendable/search": "0.0.102",
```

2023-05-25 17:03 UTC, beerose commented on .github/workflows/website.yml
> +          NEXT_PUBLIC_MENDABLE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_MENDABLE_ANON_KEY }}
Need someone to add it to github's secrets and Vercel

2023-05-26 09:58 UTC, YassinEldeeb requested changes
looks good!

I just found this issue, where the search bar wouldn't open up the dialog unless you clicked on the edges, but not in the center.


https://github.com/dotansimha/graphql-code-generator/assets/72823042/e82d5974-aed1-4071-bf58-93b0ea7ac9d6

2023-05-26 10:53 UTC, YassinEldeeb commented
maybe, it's worth highlighting in the input placeholder that is is AI search, because people might bounce when asking questions and finding that it takes longer than the normal search like Algolia

2023-05-30 18:32 UTC, YassinEldeeb commented
maybe it's worth changing either of the shortcuts of the two searches because I think currently CMD + K pops up both searches, normal and AI

<img width="1151" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/72823042/7ea6ae21-f449-4116-be1d-ccabee7c3811">

2023-05-30 21:01 UTC, saihaj approved these changes
I suppose to disable `cmd+k` on the global search bar, that is a change we need to have configurable in our global docs theme

2023-05-30 21:04 UTC, beerose commented
There's a prop in Mendable component that lets you override that. Will update it

2023-06-01 11:20 UTC, dotansimha approved these changes

2023-06-01 11:22 UTC, B2o5T commented
@beerose can we hide ctrl+k in mentabable input? currenly it's open algolia search

2023-06-01 11:25 UTC, B2o5T commented on website/theme.config.tsx
> +          <MendableSearchBar
seems we can remove the outer div? and add className directly to MendableSearchBar
<img width="369" alt="image" src="https://github.com/dotansimha/graphql-code-generator/assets/7361780/77ca1042-4eb8-4638-9fbe-6fb7b5f87a55">

2023-06-01 11:46 UTC, YassinEldeeb commented on website/theme.config.tsx
> +          <MendableSearchBar
the center or most of the search bar doesn't open the dialog on click, and it only happen on Firefox, it's fine with Chrome

![image](https://github.com/dotansimha/graphql-code-generator/assets/72823042/ae2ff890-e413-4ddc-bf41-66ce1d69308b)

2023-06-01 14:46 UTC, beerose commented
> @beerose can we hide ctrl+k in mentabable input? currenly it's open algolia search
> 
> also can we adjust bg color of input on dark theme? to be dark and not light

AFAIK, cmd+K opens algolia

2023-06-01 14:47 UTC, beerose commented on website/theme.config.tsx
> +          <MendableSearchBar
FYI that means loading a separate CSS file

2023-06-01 14:48 UTC, beerose commented
> also can we adjust bg color of input on dark theme? to be dark and not light

No, not possible in the current version of Mendable

2023-06-01 22:50 UTC, B2o5T commented on website/src/components/Search.tsx
> +// };
```suggestion
```

2023-06-01 22:50 UTC, B2o5T approved these changes

2023-06-01 22:50 UTC, merged